server:
  port: 3344

spring:
  application:
    name:  microservicedemo2-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/fupingyiye/microservicedemo2.git #GitHub上面的git仓库名字
